package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author bruna
 */
public class ConversorGUI extends javax.swing.JFrame {

    /**
     * Creates new form ConversorGUI
     */
    public ConversorGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Bg = new javax.swing.JPanel();
        tempTxt = new javax.swing.JTextField();
        converterBtn = new javax.swing.JButton();
        celsiusLbl = new javax.swing.JLabel();
        fahrenheitLbl = new javax.swing.JLabel();
        converterBtn2 = new javax.swing.JButton();
        kelvinLbl = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        BgImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Conversor Celsius");

        Bg.setBackground(new java.awt.Color(250, 204, 227));
        Bg.setLayout(null);

        tempTxt.setBackground(new java.awt.Color(204, 204, 204));
        tempTxt.setForeground(new java.awt.Color(0, 0, 0));
        tempTxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tempTxt.setSelectionColor(new java.awt.Color(0, 0, 0));
        Bg.add(tempTxt);
        tempTxt.setBounds(50, 50, 82, 23);

        converterBtn.setBackground(new java.awt.Color(204, 204, 204));
        converterBtn.setForeground(new java.awt.Color(0, 0, 0));
        converterBtn.setText("Converter");
        converterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterBtnActionPerformed(evt);
            }
        });
        Bg.add(converterBtn);
        converterBtn.setBounds(50, 80, 82, 23);

        celsiusLbl.setBackground(new java.awt.Color(0, 0, 0));
        celsiusLbl.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        celsiusLbl.setForeground(new java.awt.Color(0, 0, 0));
        celsiusLbl.setText("Celsius");
        Bg.add(celsiusLbl);
        celsiusLbl.setBounds(150, 50, 41, 30);

        fahrenheitLbl.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        fahrenheitLbl.setForeground(new java.awt.Color(0, 0, 0));
        fahrenheitLbl.setText("Fahrenheit");
        Bg.add(fahrenheitLbl);
        fahrenheitLbl.setBounds(150, 80, 110, 30);

        converterBtn2.setBackground(new java.awt.Color(204, 204, 204));
        converterBtn2.setForeground(new java.awt.Color(0, 0, 0));
        converterBtn2.setText("Converter");
        converterBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                converterBtn2ActionPerformed(evt);
            }
        });
        Bg.add(converterBtn2);
        converterBtn2.setBounds(50, 110, 82, 23);

        kelvinLbl.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        kelvinLbl.setForeground(new java.awt.Color(0, 0, 0));
        kelvinLbl.setText("Kelvin");
        Bg.add(kelvinLbl);
        kelvinLbl.setBounds(150, 110, 90, 30);

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Yu Gothic", 1, 12)); // NOI18N
        label1.setText("Conversor de Temperatura");
        Bg.add(label1);
        label1.setBounds(60, 0, 159, 24);

        BgImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/pngwing.com (1) (1).png"))); // NOI18N
        Bg.add(BgImage);
        BgImage.setBounds(10, 20, 250, 154);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Bg, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void converterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterBtnActionPerformed
        String tempFahr = controle.ConversorControle.converter(tempTxt.getText());
        fahrenheitLbl.setText(tempFahr + " Fahrenheit");
 
    }//GEN-LAST:event_converterBtnActionPerformed

    private void converterBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_converterBtn2ActionPerformed
       String tempkel = controle.ConversorControle.converterK(tempTxt.getText());
       kelvinLbl.setText(tempkel + " Kelvin");
    }//GEN-LAST:event_converterBtn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConversorGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConversorGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bg;
    private javax.swing.JLabel BgImage;
    private javax.swing.JLabel celsiusLbl;
    private javax.swing.JButton converterBtn;
    private javax.swing.JButton converterBtn2;
    private javax.swing.JLabel fahrenheitLbl;
    private javax.swing.JLabel kelvinLbl;
    private java.awt.Label label1;
    private javax.swing.JTextField tempTxt;
    // End of variables declaration//GEN-END:variables
}
